[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm exec prisma generate && pnpm turbo run build --filter=@locus/api"]

[start]
cmd = "node apps/api/dist/index.js"
